### ISSUE TITLE
macOS 安装后启动报 code() argument 13 must be str, not int 错误

### ISSUE THREAD

**Issue by mintisan** [allwefantasy/byzer-llm#23]
如题所述，是不是 macOS 目前不支持，各版本如下：

```
(base) ➜  ~ byzerllm --version
Traceback (most recent call last):
  File "/Users/mintisan/miniconda3/bin/byzerllm", line 5, in <module>
    from byzerllm.byzerllm import main
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/byzerllm/__init__.py", line 3, in <module>
    from pyjava.api.mlsql import RayContext
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/pyjava/__init__.py", line 20, in <module>
    from pyjava.api.mlsql import RayContext, PythonContext
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/pyjava/api/__init__.py", line 5, in <module>
    from pyjava.api.mlsql import PythonContext
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/pyjava/api/mlsql.py", line 11, in <module>
    import pyjava.utils as utils
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/pyjava/utils.py", line 4, in <module>
    from pyjava.serializers import write_with_length, UTF8Deserializer, \
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/pyjava/serializers.py", line 27, in <module>
    from pyjava import cloudpickle
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/pyjava/cloudpickle.py", line 174, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/pyjava/cloudpickle.py", line 136, in _make_cell_set_template_code
    return types.CodeType(
           ^^^^^^^^^^^^^^^
TypeError: code() argument 13 must be str, not int
(base) ➜  ~ pip list | grep byzerllm
byzerllm                      0.1.53
(base) ➜  ~ 
(base) ➜  ~ 
(base) ➜  ~ python --verison
unknown option --verison
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
(base) ➜  ~ python --V      
unknown option --V
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
(base) ➜  ~ python -V 
Python 3.11.5
(base) ➜  ~ 
(base) ➜  ~ auto-coder 
Traceback (most recent call last):
  File "/Users/mintisan/miniconda3/bin/auto-coder", line 5, in <module>
    from autocoder.auto_coder import main
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/autocoder/auto_coder.py", line 1, in <module>
    import byzerllm
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/byzerllm/__init__.py", line 3, in <module>
    from pyjava.api.mlsql import RayContext
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/pyjava/__init__.py", line 20, in <module>
    from pyjava.api.mlsql import RayContext, PythonContext
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/pyjava/api/__init__.py", line 5, in <module>
    from pyjava.api.mlsql import PythonContext
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/pyjava/api/mlsql.py", line 11, in <module>
    import pyjava.utils as utils
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/pyjava/utils.py", line 4, in <module>
    from pyjava.serializers import write_with_length, UTF8Deserializer, \
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/pyjava/serializers.py", line 27, in <module>
    from pyjava import cloudpickle
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/pyjava/cloudpickle.py", line 174, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mintisan/miniconda3/lib/python3.11/site-packages/pyjava/cloudpickle.py", line 136, in _make_cell_set_template_code
    return types.CodeType(
           ^^^^^^^^^^^^^^^
TypeError: code() argument 13 must be str, not int
(base) ➜  ~ pip list | grep auto-coder
auto-coder                    0.1.18
(base) ➜  ~ 
```

**Comment by allwefantasy** [comment]
使用 python 3.10.11 目前还不支持 3.11
